[package]
name = "rosu-pp-older"
version = "0.2.0"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"

[dependencies]
rosu-pp = { git = "https://github.com/MaxOhn/rosu-pp", branch = "next" }
# rosu-pp = { path = "../rosu-pp" }
rosu-map = { version = "0.1.1" }